sudo: required
services:
  - docker

before_install:
  - docker build -t naveedhuq/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true naveedhuq/react-test npm test

after_success:
  - docker build -t naveedhuq/multi-client ./client
  - docker build -t naveedhuq/multi-nginx ./nginx
  - docker build -t naveedhuq/multi-server ./server
  - docker build -t naveedhuq/multi-worker ./worker
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker Hub
  - docker push naveedhuq/multi-client
  - docker push naveedhuq/multi-nginx
  - docker push naveedhuq/multi-server
  - docker push naveedhuq/multi-worker
  
